CUDA_VISIBLE_DEVICES=0,1,5,6 vllm serve "/NAS/terencewang/model/Qwen2.5-7B-Instruct" \
    --host 0.0.0.0 \
    --port 8081 \
    --tensor-parallel-size 4 \
    --gpu-memory-utilization 0.92 \
    --enable-prefix-caching \
    --dtype auto \
    --enable-auto-tool-choice \
    --tool-call-parser hermes \
    --rope-scaling '{"rope_type":"dynamic","factor":2.0}' \
    --max-model-len 65536